//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/IndieGameProcess_178DC9ED_178dc9ed_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_ktw_wZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Programação do level_59694223_ace28822_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_ktw_wZ_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Programação do level_59694223_ace28822_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Publicação_C58AB1E8_e3895329_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,_FJnnEZ_wEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Refinar jogo_B4A57329_f226a9a6_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,_FJnnEZ_wEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Refinar jogo_B4A57329_f226a9a6_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_RGnaAZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Level design_FF556890_28db7efa_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_RGnaAZ_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Level design_FF556890_28db7efa_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Execução de level_13124F4_2c4948ab_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_vCNrEZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Validação do level_7E1D0B55_d1965154_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_vCNrEZ_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Validação do level_7E1D0B55_d1965154_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_Zuj0AaFfEeuqN_L_TCme-AActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Produção de sons_B9E4F45B_d5e3a5a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_aw7jMZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Requisitos de level_EBE85AE5_3f61a0e4_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_aw7jMZ_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Requisitos de level_EBE85AE5_3f61a0e4_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_DXq9wZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Identidade_853970EE_aebf8758_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_DXq9wZ_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Identidade_853970EE_aebf8758_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_XE9nwZ_vEeuTPu9eU-Afkw,_RZ4BAaFfEeuqN_L_TCme-AActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Produção de sprites_CB6CE250_1ee6284f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_4m0N0Z_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Integrar levels_AFD6CAB0_daeeee67_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-Afkw,_4m0N0Z_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Integrar levels_AFD6CAB0_daeeee67_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_exgSIZ_uEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Inimigos_9A7EB19E_faeaff26_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_exgSIZ_uEeuTPu9eU-AfkwWPDependency"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Inimigos_9A7EB19E_faeaff26_WPDependency.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_WDF7EZ_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Produção_9D312D22_bb2fce63_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Concepção_DB3A79F3_f9391b34_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Elaboração_E0BA48D5_feb8ea16_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_qW4Z0Z_uEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Pesquisa de Similares_9137ADC4_babdc42e_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_qW4Z0Z_uEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Pesquisa de Similares_9137ADC4_babdc42e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,__iaG8Z_vEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Testar jogo_F0C9BA41_2e4af0be_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,__iaG8Z_vEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Testar jogo_F0C9BA41_2e4af0be_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_zgbNsJ_tEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Enredo_1E47693D_7eb3b6c5_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_zgbNsJ_tEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Enredo_1E47693D_7eb3b6c5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_x4wP0Z_uEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Mecânicas_1CA980CD_462f9737_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_kwTy4J_uEeuTPu9eU-Afkw,_x4wP0Z_uEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Mecânicas_1CA980CD_462f9737_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,_LX35EZ_wEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Publicar jogo_5EE91413_9c6a4a90_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_9dSNgZ_vEeuTPu9eU-Afkw,_LX35EZ_wEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Publicar jogo_5EE91413_9c6a4a90_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_X6rkQZ_uEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Personagem_E6C15D6E_472daaf6_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_X6rkQZ_uEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Personagem_E6C15D6E_472daaf6_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_B9ctYJ_tEeuTPu9eU-AfkwActivity"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Visão geral_E5A5DB26_461228ae_Activity.jpeg"
contentPage.processPage.imageFiles["_1wbW4Z_sEeuTPu9eU-Afkw,_8WUs0Z_sEeuTPu9eU-Afkw,_B9ctYJ_tEeuTPu9eU-AfkwActivityDetail"]="./../../indie_game_process_rpp/deliveryprocesses/resources/Visão geral_E5A5DB26_461228ae_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_x8Wg8J_vEeuTPu9eU-Afkw"] = ["Refinamento de level","indie_game_process_rpp/deliveryprocesses/refinamento_de_level_48EDEE71.html"];
contentPage.processPage.elementUrls["_Uab7NJ_vEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_31B00CEC.html"];
contentPage.processPage.elementUrls["_TCQAQJ_vEeuTPu9eU-Afkw"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_25DBC8C7.html"];
contentPage.processPage.elementUrls["_XYyPcKFfEeuqN_L_TCme-A"] = ["Produção de sprites, animações e menus","indie_game_process_rpp/deliveryprocesses/produo_de_sprites_animaes_e_menus_C0AD60BA.html"];
contentPage.processPage.elementUrls["_UaciQJ_vEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_924EA15A.html"];
contentPage.processPage.elementUrls["_EDV7gJ_wEeuTPu9eU-Afkw"] = ["Testar jogo","indie_game_process_rpp/deliveryprocesses/testar_jogo_C850633.html"];
contentPage.processPage.elementUrls["_x8UrwZ_vEeuTPu9eU-Afkw"] = ["Testar level","indie_game_process_rpp/deliveryprocesses/testar_level_BA80FAAF.html"];
contentPage.processPage.elementUrls["_HEzW5p_vEeuTPu9eU-Afkw"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_2F9AE8E4.html"];
contentPage.processPage.elementUrls["_HEzW2p_vEeuTPu9eU-Afkw"] = ["Arte conceitual de personagem","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_personagem_E1E54287.html"];
contentPage.processPage.elementUrls["_bTRQtJ_uEeuTPu9eU-Afkw"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_9FB2BD75.html"];
contentPage.processPage.elementUrls["_DXq9wZ_vEeuTPu9eU-Afkw"] = ["Identidade","indie_game_process_rpp/deliveryprocesses/Identidade_853970EE.html"];
contentPage.processPage.elementUrls["_UaciRp_vEeuTPu9eU-Afkw"] = ["Arte conceitual de ambiente","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_ambiente_5017779F.html"];
contentPage.processPage.elementUrls["_cFiScqFfEeuqN_L_TCme-A"] = ["Artes de um level","indie_game_process_rpp/deliveryprocesses/artes_de_um_level_812AE075.html"];
contentPage.processPage.elementUrls["_HEwTgp_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_74346A92.html"];
contentPage.processPage.elementUrls["_ebJyNJ_vEeuTPu9eU-Afkw"] = ["Arte conceitual de personagem","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_personagem_F565C737.html"];
contentPage.processPage.elementUrls["_WE7jlp_uEeuTPu9eU-Afkw"] = ["Objetivo do jogo","indie_game_process_rpp/deliveryprocesses/objetivo_do_jogo_97372913.html"];
contentPage.processPage.elementUrls["_XY0EoKFfEeuqN_L_TCme-A"] = ["Arte conceitual de ambiente","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_ambiente_140BA5CC.html"];
contentPage.processPage.elementUrls["_WE7jkp_uEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_D2A546F4.html"];
contentPage.processPage.elementUrls["_x8VS1J_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_EFFF4625.html"];
contentPage.processPage.elementUrls["_WE6VcZ_uEeuTPu9eU-Afkw"] = ["Enredo","indie_game_process_rpp/deliveryprocesses/enredo_C68BA873.html"];
contentPage.processPage.elementUrls["_bTRQsJ_uEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_DB20DB56.html"];
contentPage.processPage.elementUrls["_oJ4hUJ_vEeuTPu9eU-Afkw"] = ["Artes requisitadas","indie_game_process_rpp/deliveryprocesses/artes_requisitadas_D80C5233.html"];
contentPage.processPage.elementUrls["_msrjgJ_vEeuTPu9eU-Afkw"] = ["Condições de vitória e derrota","indie_game_process_rpp/deliveryprocesses/condies_de_vitria_e_derrota_5648C350.html"];
contentPage.processPage.elementUrls["_TCPZM5_vEeuTPu9eU-Afkw"] = ["Mecanicas de perigo","indie_game_process_rpp/deliveryprocesses/mecanicas_de_perigo_A3A6BFB0.html"];
contentPage.processPage.elementUrls["_TCPZMZ_vEeuTPu9eU-Afkw"] = ["Mecanicas de combate","indie_game_process_rpp/deliveryprocesses/mecanicas_de_combate_4C33D5D5.html"];
contentPage.processPage.elementUrls["_ebJySJ_vEeuTPu9eU-Afkw"] = ["Mecanicas do personagem","indie_game_process_rpp/deliveryprocesses/mecanicas_do_personagem_CC3F31D2.html"];
contentPage.processPage.elementUrls["_msqVYJ_vEeuTPu9eU-Afkw"] = ["Codificar mecânicas","indie_game_process_rpp/deliveryprocesses/codificar_mecnicas_9D5CEC2B.html"];
contentPage.processPage.elementUrls["_x8VS0p_vEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_24A4582C.html"];
contentPage.processPage.elementUrls["_oJ5IZJ_vEeuTPu9eU-Afkw"] = ["Integração de level design","indie_game_process_rpp/deliveryprocesses/integrao_de_level_design_AEE5BCCE.html"];
contentPage.processPage.elementUrls["_bTQCkJ_uEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_8F9E9B71.html"];
contentPage.processPage.elementUrls["_bTR3wJ_uEeuTPu9eU-Afkw"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_D370EF34.html"];
contentPage.processPage.elementUrls["_6cFtYp_vEeuTPu9eU-Afkw"] = ["Integração de level design","indie_game_process_rpp/deliveryprocesses/integrao_de_level_design_1811E2C1.html"];
contentPage.processPage.elementUrls["_4m0N0Z_vEeuTPu9eU-Afkw"] = ["Integrar levels","indie_game_process_rpp/deliveryprocesses/Integrar levels_AFD6CAB0.html"];
contentPage.processPage.elementUrls["_-PwBsp_uEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_35AC97F9.html"];
contentPage.processPage.elementUrls["_vfFpxp_uEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_1C70DB80.html"];
contentPage.processPage.elementUrls["_WE68gJ_uEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_B43DDC41.html"];
contentPage.processPage.elementUrls["_XY0EqqFfEeuqN_L_TCme-A"] = ["Artes requisitadas","indie_game_process_rpp/deliveryprocesses/artes_requisitadas_96665E30.html"];
contentPage.processPage.elementUrls["_ebKZRZ_vEeuTPu9eU-Afkw"] = ["Sons requistados","indie_game_process_rpp/deliveryprocesses/sons_requistados_124B2FC3.html"];
contentPage.processPage.elementUrls["_-Ps-YJ_uEeuTPu9eU-Afkw"] = ["Condições de jogo","indie_game_process_rpp/deliveryprocesses/condies_de_jogo_C8234E5C.html"];
contentPage.processPage.elementUrls["_ebH9AJ_vEeuTPu9eU-Afkw"] = ["Artes do level","indie_game_process_rpp/deliveryprocesses/artes_do_level_C0212EA6.html"];
contentPage.processPage.elementUrls["_FJnnEZ_wEeuTPu9eU-Afkw"] = ["Refinar jogo","indie_game_process_rpp/deliveryprocesses/Refinar jogo_B4A57329.html"];
contentPage.processPage.elementUrls["_bTR3wp_uEeuTPu9eU-Afkw"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_CCA7E35A.html"];
contentPage.processPage.elementUrls["_OSVfFp_wEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_6F65738E.html"];
contentPage.processPage.elementUrls["_x8VS0J_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_2B6D6406.html"];
contentPage.processPage.elementUrls["_HaYIxJ_wEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_47FA6C6B.html"];
contentPage.processPage.elementUrls["_-PwBwp_uEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_47F42075.html"];
contentPage.processPage.elementUrls["_TCQAQp_vEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_1F12BCED.html"];
contentPage.processPage.elementUrls["_vfFpwJ_uEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_5EA8053B.html"];
contentPage.processPage.elementUrls["_XY0EqKFfEeuqN_L_TCme-A"] = ["Tipografia","indie_game_process_rpp/deliveryprocesses/tipografia_9D2F6A0A.html"];
contentPage.processPage.elementUrls["_6cEfQJ_vEeuTPu9eU-Afkw"] = ["Integrar levels","indie_game_process_rpp/deliveryprocesses/integrar_levels_D358AEB6.html"];
contentPage.processPage.elementUrls["_-PwBup_uEeuTPu9eU-Afkw"] = ["Mecanicas do personagem","indie_game_process_rpp/deliveryprocesses/mecanicas_do_personagem_BED05C37.html"];
contentPage.processPage.elementUrls["_oJ1eBJ_vEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_2153E186.html"];
contentPage.processPage.elementUrls["_-Ps-YZ_uEeuTPu9eU-Afkw"] = ["Mecanicas de combate","indie_game_process_rpp/deliveryprocesses/mecanicas_de_combate_D2C12E6C.html"];
contentPage.processPage.elementUrls["_-PwByJ_uEeuTPu9eU-Afkw"] = ["Caracteristicas dos inimigos","indie_game_process_rpp/deliveryprocesses/caracteristicas_dos_inimigos_D7E0F08D.html"];
contentPage.processPage.elementUrls["_bTPbgJ_uEeuTPu9eU-Afkw"] = ["Back history personagem","indie_game_process_rpp/deliveryprocesses/back_history_personagem_7D5712F5.html"];
contentPage.processPage.elementUrls["_TCQARJ_vEeuTPu9eU-Afkw"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_EA6DAAE6.html"];
contentPage.processPage.elementUrls["_lGNm4p_tEeuTPu9eU-Afkw"] = ["Definir ideia e objetivo do jogo","indie_game_process_rpp/deliveryprocesses/definir_objetivo_do_jogo_9825E9E3.html"];
contentPage.processPage.elementUrls["_bTRQsp_uEeuTPu9eU-Afkw"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_D457CF7C.html"];
contentPage.processPage.elementUrls["_UaaGAJ_vEeuTPu9eU-Afkw"] = ["Produção de level design","indie_game_process_rpp/deliveryprocesses/produo_de_level_design_294BD70A.html"];
contentPage.processPage.elementUrls["_XY0EpKFfEeuqN_L_TCme-A"] = ["Arte conceitual de personagem","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_personagem_D89D87EB.html"];
contentPage.processPage.elementUrls["_WE7jkJ_uEeuTPu9eU-Afkw"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_D96E52CE.html"];
contentPage.processPage.elementUrls["_ebJyOJ_vEeuTPu9eU-Afkw"] = ["Tipografia","indie_game_process_rpp/deliveryprocesses/tipografia_B9F7A956.html"];
contentPage.processPage.elementUrls["_hqIhkJ_tEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_46CACE74.html"];
contentPage.processPage.elementUrls["__iaG8Z_vEeuTPu9eU-Afkw"] = ["Testar jogo","indie_game_process_rpp/deliveryprocesses/Testar jogo_F0C9BA41.html"];
contentPage.processPage.elementUrls["_WE7jmp_uEeuTPu9eU-Afkw"] = ["Titulo do jogo","indie_game_process_rpp/deliveryprocesses/titulo_do_jogo_5BC90B32.html"];
contentPage.processPage.elementUrls["_cFdZ8KFfEeuqN_L_TCme-A"] = ["Produção de músicas e efeitos sonoros","indie_game_process_rpp/deliveryprocesses/produo_de_msicas_e_efeitos_sonoros_9CF26D86.html"];
contentPage.processPage.elementUrls["_TCOyIp_vEeuTPu9eU-Afkw"] = ["Condições de vitória e derrota","indie_game_process_rpp/deliveryprocesses/condies_de_vitria_e_derrota_2885616F.html"];
contentPage.processPage.elementUrls["_vCNrEZ_vEeuTPu9eU-Afkw"] = ["Validação do level","indie_game_process_rpp/deliveryprocesses/Validação do level_7E1D0B55.html"];
contentPage.processPage.elementUrls["_EDWil5_wEeuTPu9eU-Afkw"] = ["Jogo","indie_game_process_rpp/deliveryprocesses/jogo_585828CA.html"];
contentPage.processPage.elementUrls["_Zuj0AaFfEeuqN_L_TCme-A"] = ["Produção de sons","indie_game_process_rpp/deliveryprocesses/Produção de sons_B9E4F45B.html"];
contentPage.processPage.elementUrls["_ebJyMp_vEeuTPu9eU-Afkw"] = ["Arte conceitual de inimigos","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_inimigos_2A0AD93E.html"];
contentPage.processPage.elementUrls["_X6rkQZ_uEeuTPu9eU-Afkw"] = ["Personagem","indie_game_process_rpp/deliveryprocesses/Personagem_E6C15D6E.html"];
contentPage.processPage.elementUrls["_XY0rsKFfEeuqN_L_TCme-A"] = ["Artes de um level","indie_game_process_rpp/deliveryprocesses/artes_de_um_level_4D465D35.html"];
contentPage.processPage.elementUrls["_ebH9Ap_vEeuTPu9eU-Afkw"] = ["Sons do level","indie_game_process_rpp/deliveryprocesses/sons_do_level_B95822CC.html"];
contentPage.processPage.elementUrls["_-PwBtJ_uEeuTPu9eU-Afkw"] = ["Mecanicas de combate","indie_game_process_rpp/deliveryprocesses/mecanicas_de_combate_10785F2.html"];
contentPage.processPage.elementUrls["_x8VS2J_vEeuTPu9eU-Afkw"] = ["Playtest","indie_game_process_rpp/deliveryprocesses/playtest_B4912844.html"];
contentPage.processPage.elementUrls["_WDF7EZ_vEeuTPu9eU-Afkw"] = ["Produção","indie_game_process_rpp/deliveryprocesses/Produção_9D312D22.html"];
contentPage.processPage.elementUrls["_TCOyIJ_vEeuTPu9eU-Afkw"] = ["Caracteristicas dos inimigos","indie_game_process_rpp/deliveryprocesses/caracteristicas_dos_inimigos_2F4E6D49.html"];
contentPage.processPage.elementUrls["_ebJyRJ_vEeuTPu9eU-Afkw"] = ["Mecanicas de perigo","indie_game_process_rpp/deliveryprocesses/mecanicas_de_perigo_7AD4FB3.html"];
contentPage.processPage.elementUrls["_HEwTgJ_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_7AFD766C.html"];
contentPage.processPage.elementUrls["_XY0ErqFfEeuqN_L_TCme-A"] = ["Informações de level design","indie_game_process_rpp/deliveryprocesses/informaes_de_level_design_5AF8404F.html"];
contentPage.processPage.elementUrls["_zgbNsJ_tEeuTPu9eU-Afkw"] = ["Enredo","indie_game_process_rpp/deliveryprocesses/Enredo_1E47693D.html"];
contentPage.processPage.elementUrls["_UaciRJ_vEeuTPu9eU-Afkw"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_56E08379.html"];
contentPage.processPage.elementUrls["_ebJLJJ_vEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_BC2B0FCE.html"];
contentPage.processPage.elementUrls["_kAL9jJ_uEeuTPu9eU-Afkw"] = ["Caracteristicas dos inimigos","indie_game_process_rpp/deliveryprocesses/caracteristicas_dos_inimigos_7950EF1.html"];
contentPage.processPage.elementUrls["_x8UrwJ_vEeuTPu9eU-Afkw"] = ["Refinar level design","indie_game_process_rpp/deliveryprocesses/refinar_level_design_AFE31A9F.html"];
contentPage.processPage.elementUrls["_ebJyNp_vEeuTPu9eU-Afkw"] = ["Paleta de cores e estilo de arte","indie_game_process_rpp/deliveryprocesses/paleta_de_cores_e_estilo_de_arte_EE9CBB5D.html"];
contentPage.processPage.elementUrls["_cFeoEKFfEeuqN_L_TCme-A"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_5EF6C44D.html"];
contentPage.processPage.elementUrls["_EDV7g5_wEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_6E95D01E.html"];
contentPage.processPage.elementUrls["_HEzW6p_vEeuTPu9eU-Afkw"] = ["Tema do jogo","indie_game_process_rpp/deliveryprocesses/tema_do_jogo_F42CCB03.html"];
contentPage.processPage.elementUrls["_WE6Vcp_uEeuTPu9eU-Afkw"] = ["Mundo","indie_game_process_rpp/deliveryprocesses/mundo_B524BC89.html"];
contentPage.processPage.elementUrls["_cFhrZKFfEeuqN_L_TCme-A"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_9ED2F938.html"];
contentPage.processPage.elementUrls["_HaYv0J_wEeuTPu9eU-Afkw"] = ["Jogo","indie_game_process_rpp/deliveryprocesses/jogo_25E602A0.html"];
contentPage.processPage.elementUrls["_OSWGIJ_wEeuTPu9eU-Afkw"] = ["Jogo","indie_game_process_rpp/deliveryprocesses/jogo_C3E425C5.html"];
contentPage.processPage.elementUrls["_ebJyPJ_vEeuTPu9eU-Afkw"] = ["Informações de level design","indie_game_process_rpp/deliveryprocesses/informaes_de_level_design_7E898B75.html"];
contentPage.processPage.elementUrls["_Uab7Mp_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_66551EF3.html"];
contentPage.processPage.elementUrls["_mssKkJ_vEeuTPu9eU-Afkw"] = ["Mecanicas do personagem","indie_game_process_rpp/deliveryprocesses/mecanicas_do_personagem_68904BCC.html"];
contentPage.processPage.elementUrls["_-PwBxJ_uEeuTPu9eU-Afkw"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_134F0E6E.html"];
contentPage.processPage.elementUrls["_-PwBwJ_uEeuTPu9eU-Afkw"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_4EBD2C4F.html"];
contentPage.processPage.elementUrls["_ktw_wZ_vEeuTPu9eU-Afkw"] = ["Programação do level","indie_game_process_rpp/deliveryprocesses/Programação do level_59694223.html"];
contentPage.processPage.elementUrls["_ebJyPp_vEeuTPu9eU-Afkw"] = ["Level design","indie_game_process_rpp/deliveryprocesses/level_design_77C07F9B.html"];
contentPage.processPage.elementUrls["_msq8cJ_vEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_31184CC3.html"];
contentPage.processPage.elementUrls["_Uab7MJ_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_6D1E2ACD.html"];
contentPage.processPage.elementUrls["_lGNm4J_tEeuTPu9eU-Afkw"] = ["Definir o gênero de jogo","indie_game_process_rpp/deliveryprocesses/definir_o_gnero_de_jogo_9EEEF5BD.html"];
contentPage.processPage.elementUrls["_EDV7gZ_wEeuTPu9eU-Afkw"] = ["Playtest","indie_game_process_rpp/deliveryprocesses/playtest_1722E643.html"];
contentPage.processPage.elementUrls["_bP0EA6FiEeuqN_L_TCme-A"] = ["Tema do jogo","indie_game_process_rpp/deliveryprocesses/tema_do_jogo_150B595.html"];
contentPage.processPage.elementUrls["_EDWik5_wEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_93C646AB.html"];
contentPage.processPage.elementUrls["_x8Wg8p_vEeuTPu9eU-Afkw"] = ["Integração de level design","indie_game_process_rpp/deliveryprocesses/integrao_de_level_design_4224E297.html"];
contentPage.processPage.elementUrls["_hqH6gJ_tEeuTPu9eU-Afkw"] = ["Definir tematica de jogo","indie_game_process_rpp/deliveryprocesses/definir_tematica_de_jogo_219A57E7.html"];
contentPage.processPage.elementUrls["_ebJyRp_vEeuTPu9eU-Afkw"] = ["Mecanicas de recompensa","indie_game_process_rpp/deliveryprocesses/mecanicas_de_recompensa_E443D9.html"];
contentPage.processPage.elementUrls["_ebKZQ5_vEeuTPu9eU-Afkw"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_A52C377F.html"];
contentPage.processPage.elementUrls["_ebJLIp_vEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_F0D021D5.html"];
contentPage.processPage.elementUrls["_XY0EpqFfEeuqN_L_TCme-A"] = ["Paleta de cores e estilo de arte","indie_game_process_rpp/deliveryprocesses/paleta_de_cores_e_estilo_de_arte_D1D47C11.html"];
contentPage.processPage.elementUrls["_lGNm4Z_tEeuTPu9eU-Afkw"] = ["Definir o titulo do jogo","indie_game_process_rpp/deliveryprocesses/definir_o_titulo_do_jogo_A98CD5CD.html"];
contentPage.processPage.elementUrls["_-PwBsJ_uEeuTPu9eU-Afkw"] = ["Mecanicas do personagem","indie_game_process_rpp/deliveryprocesses/mecanicas_do_personagem_3C75A3D3.html"];
contentPage.processPage.elementUrls["_HEzW7p_vEeuTPu9eU-Afkw"] = ["Tipografia","indie_game_process_rpp/deliveryprocesses/tipografia_B8BEAD22.html"];
contentPage.processPage.elementUrls["_cFiScKFfEeuqN_L_TCme-A"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_87F3EC4F.html"];
contentPage.processPage.elementUrls["_oJ4hUp_vEeuTPu9eU-Afkw"] = ["Sons requistados","indie_game_process_rpp/deliveryprocesses/sons_requistados_D1434659.html"];
contentPage.processPage.elementUrls["_ebJyQJ_vEeuTPu9eU-Afkw"] = ["Condições de vitória e derrota","indie_game_process_rpp/deliveryprocesses/condies_de_vitria_e_derrota_431B6D94.html"];
contentPage.processPage.elementUrls["_x8VS1p_vEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_E9363A4B.html"];
contentPage.processPage.elementUrls["_6cFtYJ_vEeuTPu9eU-Afkw"] = ["Level design","indie_game_process_rpp/deliveryprocesses/level_design_1EDAEE9B.html"];
contentPage.processPage.elementUrls["_HEzW0p_vEeuTPu9eU-Afkw"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_58C17E49.html"];
contentPage.processPage.elementUrls["_WE7jlJ_uEeuTPu9eU-Afkw"] = ["Gênero de jogo","indie_game_process_rpp/deliveryprocesses/gnero_de_jogo_9E0034ED.html"];
contentPage.processPage.elementUrls["_RGnaAZ_vEeuTPu9eU-Afkw"] = ["Level design","indie_game_process_rpp/deliveryprocesses/Level design_FF556890.html"];
contentPage.processPage.elementUrls["_UaciTJ_vEeuTPu9eU-Afkw"] = ["Identidade sonora","indie_game_process_rpp/deliveryprocesses/identidade_sonora_E00447B7.html"];
contentPage.processPage.elementUrls["_TCQARp_vEeuTPu9eU-Afkw"] = ["Informações de level design","indie_game_process_rpp/deliveryprocesses/informaes_de_level_design_E3A49F0C.html"];
contentPage.processPage.elementUrls["_msrjgp_vEeuTPu9eU-Afkw"] = ["Mecanicas de combate","indie_game_process_rpp/deliveryprocesses/mecanicas_de_combate_4F7FB776.html"];
contentPage.processPage.elementUrls["_ebJyOp_vEeuTPu9eU-Afkw"] = ["Artes requisitadas","indie_game_process_rpp/deliveryprocesses/artes_requisitadas_B32E9D7C.html"];
contentPage.processPage.elementUrls["_EDWilZ_wEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_E53EEF.html"];
contentPage.processPage.elementUrls["_kwTy4J_uEeuTPu9eU-Afkw"] = ["Elaboração","indie_game_process_rpp/deliveryprocesses/Elaboração_E0BA48D5.html"];
contentPage.processPage.elementUrls["_UaciQp_vEeuTPu9eU-Afkw"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_8B859580.html"];
contentPage.processPage.elementUrls["_mssKlJ_vEeuTPu9eU-Afkw"] = ["Mecanicas requisitadas","indie_game_process_rpp/deliveryprocesses/mecanicas_requisitadas_2D222DEB.html"];
contentPage.processPage.elementUrls["_HEzW3J_vEeuTPu9eU-Afkw"] = ["Identidade sonora","indie_game_process_rpp/deliveryprocesses/identidade_sonora_AD403080.html"];
contentPage.processPage.elementUrls["_x8Wg9J_vEeuTPu9eU-Afkw"] = ["Feedback de level","indie_game_process_rpp/deliveryprocesses/feedback_de_level_D7FD090.html"];
contentPage.processPage.elementUrls["_HaYv0p_wEeuTPu9eU-Afkw"] = ["Feedback do jogo","indie_game_process_rpp/deliveryprocesses/feedback_do_jogo_1F1CF6C6.html"];
contentPage.processPage.elementUrls["_HEzW1p_vEeuTPu9eU-Afkw"] = ["Arte conceitual de ambiente","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_ambiente_1D536068.html"];
contentPage.processPage.elementUrls["_TCPZOZ_vEeuTPu9eU-Afkw"] = ["Mecanicas dos inimigos","indie_game_process_rpp/deliveryprocesses/mecanicas_dos_inimigos_D5579A13.html"];
contentPage.processPage.elementUrls["_HEzW0J_vEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_5F8A8A23.html"];
contentPage.processPage.elementUrls["_cFhrYKFfEeuqN_L_TCme-A"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_DA411719.html"];
contentPage.processPage.elementUrls["_x4wP0Z_uEeuTPu9eU-Afkw"] = ["Mecânicas","indie_game_process_rpp/deliveryprocesses/Mecânicas_1CA980CD.html"];
contentPage.processPage.elementUrls["_RZ4BAaFfEeuqN_L_TCme-A"] = ["Produção de sprites","indie_game_process_rpp/deliveryprocesses/Produção de sprites_CB6CE250.html"];
contentPage.processPage.elementUrls["_TCPZN5_vEeuTPu9eU-Afkw"] = ["Mecanicas do personagem","indie_game_process_rpp/deliveryprocesses/mecanicas_do_personagem_6838A1CF.html"];
contentPage.processPage.elementUrls["_UaciTp_vEeuTPu9eU-Afkw"] = ["Paleta de cores e estilo de arte","indie_game_process_rpp/deliveryprocesses/paleta_de_cores_e_estilo_de_arte_D93B3BDD.html"];
contentPage.processPage.elementUrls["_bTRQtp_uEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_98E9B19B.html"];
contentPage.processPage.elementUrls["_ebJyQp_vEeuTPu9eU-Afkw"] = ["Mecanicas de combate","indie_game_process_rpp/deliveryprocesses/mecanicas_de_combate_3C5261BA.html"];
contentPage.processPage.elementUrls["_bTPbgZ_uEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem ","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem__87F4F305.html"];
contentPage.processPage.elementUrls["_HEzW2J_vEeuTPu9eU-Afkw"] = ["Arte conceitual de inimigos","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_inimigos_E8AE4E61.html"];
contentPage.processPage.elementUrls["_OSVfEp_wEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_AAD3916F.html"];
contentPage.processPage.elementUrls["_-Ps-Y5_uEeuTPu9eU-Afkw"] = ["Mecanicas de recompensa","indie_game_process_rpp/deliveryprocesses/mecanicas_de_recompensa_2A341847.html"];
contentPage.processPage.elementUrls["_vfFCsJ_uEeuTPu9eU-Afkw"] = ["Pesquisa de similares","indie_game_process_rpp/deliveryprocesses/pesquisa_de_similares_256D4DD2.html"];
contentPage.processPage.elementUrls["_HaYIwJ_wEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_83688A4C.html"];
contentPage.processPage.elementUrls["_lGON8p_tEeuTPu9eU-Afkw"] = ["Titulo do jogo","indie_game_process_rpp/deliveryprocesses/titulo_do_jogo_AA6D725F.html"];
contentPage.processPage.elementUrls["_cFhrYqFfEeuqN_L_TCme-A"] = ["Level design","indie_game_process_rpp/deliveryprocesses/level_design_D3780B3F.html"];
contentPage.processPage.elementUrls["_kAL9gp_uEeuTPu9eU-Afkw"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_B3165CBA.html"];
contentPage.processPage.elementUrls["_cFhrZqFfEeuqN_L_TCme-A"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_9809ED5E.html"];
contentPage.processPage.elementUrls["_OSVfFJ_wEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_762E7F68.html"];
contentPage.processPage.elementUrls["_6cFGVp_vEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_A3690D77.html"];
contentPage.processPage.elementUrls["_UabUIJ_vEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_74CE16EF.html"];
contentPage.processPage.elementUrls["_HEzW7J_vEeuTPu9eU-Afkw"] = ["Caracteristicas dos inimigos","indie_game_process_rpp/deliveryprocesses/caracteristicas_dos_inimigos_BF87B8FC.html"];
contentPage.processPage.elementUrls["_cFiSeKFfEeuqN_L_TCme-A"] = ["Sons de um level","indie_game_process_rpp/deliveryprocesses/sons_de_um_level_1117B08D.html"];
contentPage.processPage.elementUrls["_WE6VcJ_uEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_BBEDC863.html"];
contentPage.processPage.elementUrls["_bTPbgp_uEeuTPu9eU-Afkw"] = ["Enredo: Personagem","indie_game_process_rpp/deliveryprocesses/enredo_personagem_768E071B.html"];
contentPage.processPage.elementUrls["_bP0EAKFiEeuqN_L_TCme-A"] = ["Objetivo do jogo","indie_game_process_rpp/deliveryprocesses/objetivo_do_jogo_9F3FEBAA.html"];
contentPage.processPage.elementUrls["_1wbW4Z_sEeuTPu9eU-Afkw"] = ["IndieGameProcess","indie_game_process_rpp/deliveryprocesses/IndieGameProcess_178DC9ED.html"];
contentPage.processPage.elementUrls["_-PwBvp_uEeuTPu9eU-Afkw"] = ["Condições de vitória e derrota","indie_game_process_rpp/deliveryprocesses/condies_de_vitria_e_derrota_83623E56.html"];
contentPage.processPage.elementUrls["_HEqM4Z_vEeuTPu9eU-Afkw"] = ["Construcao da identidade visual","indie_game_process_rpp/deliveryprocesses/construcao_da_identidade_visual_4F1797CE.html"];
contentPage.processPage.elementUrls["_cFiSdqFfEeuqN_L_TCme-A"] = ["Sons requistados","indie_game_process_rpp/deliveryprocesses/sons_requistados_45BCC294.html"];
contentPage.processPage.elementUrls["_ebJyMJ_vEeuTPu9eU-Afkw"] = ["Arte conceitual de ambiente","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_ambiente_30D3E518.html"];
contentPage.processPage.elementUrls["_vfGQ0J_uEeuTPu9eU-Afkw"] = ["Gênero de jogo","indie_game_process_rpp/deliveryprocesses/gnero_de_jogo_DA324EA2.html"];
contentPage.processPage.elementUrls["_ebJySp_vEeuTPu9eU-Afkw"] = ["Mecanicas dos inimigos","indie_game_process_rpp/deliveryprocesses/mecanicas_dos_inimigos_C57625F8.html"];
contentPage.processPage.elementUrls["_-PwBsZ_uEeuTPu9eU-Afkw"] = ["Mecânicas dos inimigos","indie_game_process_rpp/deliveryprocesses/mecnicas_dos_inimigos_471383E3.html"];
contentPage.processPage.elementUrls["_-Ps-Yp_uEeuTPu9eU-Afkw"] = ["Mecanicas de perigo","indie_game_process_rpp/deliveryprocesses/mecanicas_de_perigo_C15A4282.html"];
contentPage.processPage.elementUrls["_6cFtZp_vEeuTPu9eU-Afkw"] = ["Jogo","indie_game_process_rpp/deliveryprocesses/jogo_DCA3C4E0.html"];
contentPage.processPage.elementUrls["_hqJIoJ_tEeuTPu9eU-Afkw"] = ["Tema do jogo","indie_game_process_rpp/deliveryprocesses/tema_do_jogo_591256F0.html"];
contentPage.processPage.elementUrls["_HEqM4J_vEeuTPu9eU-Afkw"] = ["Construcao da identidade sonora","indie_game_process_rpp/deliveryprocesses/construcao_da_identidade_sonora_4479B7BE.html"];
contentPage.processPage.elementUrls["_UaciUp_vEeuTPu9eU-Afkw"] = ["Level design","indie_game_process_rpp/deliveryprocesses/level_design_9DCD1DFC.html"];
contentPage.processPage.elementUrls["_-PwBuJ_uEeuTPu9eU-Afkw"] = ["Mecanicas de recompensa","indie_game_process_rpp/deliveryprocesses/mecanicas_de_recompensa_C5996811.html"];
contentPage.processPage.elementUrls["_cFiSdKFfEeuqN_L_TCme-A"] = ["Mecanicas requisitadas","indie_game_process_rpp/deliveryprocesses/mecanicas_requisitadas_4C85CE6E.html"];
contentPage.processPage.elementUrls["_XYy2gKFfEeuqN_L_TCme-A"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_B8FD7498.html"];
contentPage.processPage.elementUrls["_HEzW3p_vEeuTPu9eU-Afkw"] = ["Paleta de cores e estilo de arte","indie_game_process_rpp/deliveryprocesses/paleta_de_cores_e_estilo_de_arte_A67724A6.html"];
contentPage.processPage.elementUrls["_ebH9AZ_vEeuTPu9eU-Afkw"] = ["Mecanicas do level","indie_game_process_rpp/deliveryprocesses/mecanicas_do_level_CABF0EB6.html"];
contentPage.processPage.elementUrls["_oJ5IYp_vEeuTPu9eU-Afkw"] = ["Sons de um level","indie_game_process_rpp/deliveryprocesses/sons_de_um_level_E38ACED5.html"];
contentPage.processPage.elementUrls["_XE9nwZ_vEeuTPu9eU-Afkw"] = ["Execução de level","indie_game_process_rpp/deliveryprocesses/Execução de level_13124F4.html"];
contentPage.processPage.elementUrls["_XY0ErKFfEeuqN_L_TCme-A"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_61C14C29.html"];
contentPage.processPage.elementUrls["_vfGQ0p_uEeuTPu9eU-Afkw"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_D36942C8.html"];
contentPage.processPage.elementUrls["_TCM88J_vEeuTPu9eU-Afkw"] = ["Definir level design","indie_game_process_rpp/deliveryprocesses/definir_level_design_1A17EA7B.html"];
contentPage.processPage.elementUrls["_6cFGUp_vEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_DED72B58.html"];
contentPage.processPage.elementUrls["_HEzW4p_vEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_6B0906C5.html"];
contentPage.processPage.elementUrls["_oJ1eAJ_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_5CC1FF67.html"];
contentPage.processPage.elementUrls["_XY0EsKFfEeuqN_L_TCme-A"] = ["Level design","indie_game_process_rpp/deliveryprocesses/level_design_26532E48.html"];
contentPage.processPage.elementUrls["_kAL9ip_uEeuTPu9eU-Afkw"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_3C3A20F8.html"];
contentPage.processPage.elementUrls["_6cFGVJ_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_AA321951.html"];
contentPage.processPage.elementUrls["_oJ5IYJ_vEeuTPu9eU-Afkw"] = ["Artes de um level","indie_game_process_rpp/deliveryprocesses/artes_de_um_level_EA53DAAF.html"];
contentPage.processPage.elementUrls["_kAL9gJ_uEeuTPu9eU-Afkw"] = ["Back history","indie_game_process_rpp/deliveryprocesses/back_history_B9DF6894.html"];
contentPage.processPage.elementUrls["_kAL9iJ_uEeuTPu9eU-Afkw"] = ["Caracteristicas do personagem","indie_game_process_rpp/deliveryprocesses/caracteristicas_do_personagem_43032CD2.html"];
contentPage.processPage.elementUrls["_kAL9hp_uEeuTPu9eU-Afkw"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_77A83ED9.html"];
contentPage.processPage.elementUrls["_-PwBvJ_uEeuTPu9eU-Afkw"] = ["Mecanicas dos inimigos","indie_game_process_rpp/deliveryprocesses/mecanicas_dos_inimigos_8A2B4A30.html"];
contentPage.processPage.elementUrls["_6cFtZJ_vEeuTPu9eU-Afkw"] = ["Refinamento de level","indie_game_process_rpp/deliveryprocesses/refinamento_de_level_E36CD0BA.html"];
contentPage.processPage.elementUrls["_bP0rEaFiEeuqN_L_TCme-A"] = ["Enredo do jogo","indie_game_process_rpp/deliveryprocesses/enredo_do_jogo_C713B729.html"];
contentPage.processPage.elementUrls["_qW4Z0Z_uEeuTPu9eU-Afkw"] = ["Pesquisa de Similares","indie_game_process_rpp/deliveryprocesses/Pesquisa de Similares_9137ADC4.html"];
contentPage.processPage.elementUrls["_msrjhp_vEeuTPu9eU-Afkw"] = ["Mecanicas de recompensa","indie_game_process_rpp/deliveryprocesses/mecanicas_de_recompensa_14119995.html"];
contentPage.processPage.elementUrls["_lGON9J_tEeuTPu9eU-Afkw"] = ["Gênero de jogo","indie_game_process_rpp/deliveryprocesses/gnero_de_jogo_75C86058.html"];
contentPage.processPage.elementUrls["_6cFGUJ_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_E5A03732.html"];
contentPage.processPage.elementUrls["_-PwBtp_uEeuTPu9eU-Afkw"] = ["Mecanicas de perigo","indie_game_process_rpp/deliveryprocesses/mecanicas_de_perigo_FA3E7A18.html"];
contentPage.processPage.elementUrls["_oJ1eAp_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_55F8F38D.html"];
contentPage.processPage.elementUrls["_HEzW6J_vEeuTPu9eU-Afkw"] = ["Gênero de jogo","indie_game_process_rpp/deliveryprocesses/gnero_de_jogo_FAF5D6DD.html"];
contentPage.processPage.elementUrls["_oJ028J_vEeuTPu9eU-Afkw"] = ["Integrar assets","indie_game_process_rpp/deliveryprocesses/integrar_assets_930DBC7E.html"];
contentPage.processPage.elementUrls["_vfFpwp_uEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_57DEF961.html"];
contentPage.processPage.elementUrls["_HEzW1J_vEeuTPu9eU-Afkw"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_241C6C42.html"];
contentPage.processPage.elementUrls["_9dSNgZ_vEeuTPu9eU-Afkw"] = ["Publicação","indie_game_process_rpp/deliveryprocesses/Publicação_C58AB1E8.html"];
contentPage.processPage.elementUrls["_EDWimZ_wEeuTPu9eU-Afkw"] = ["Feedback do jogo","indie_game_process_rpp/deliveryprocesses/feedback_do_jogo_C577210E.html"];
contentPage.processPage.elementUrls["_EDWikZ_wEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_3C535CD0.html"];
contentPage.processPage.elementUrls["_WE7jmJ_uEeuTPu9eU-Afkw"] = ["Tema do jogo","indie_game_process_rpp/deliveryprocesses/tema_do_jogo_6292170C.html"];
contentPage.processPage.elementUrls["_mssKkp_vEeuTPu9eU-Afkw"] = ["Mecanicas dos inimigos","indie_game_process_rpp/deliveryprocesses/mecanicas_dos_inimigos_61C73FF2.html"];
contentPage.processPage.elementUrls["_ebJLIJ_vEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_F7992DAF.html"];
contentPage.processPage.elementUrls["_mssKlp_vEeuTPu9eU-Afkw"] = ["Mecanicas codificadas","indie_game_process_rpp/deliveryprocesses/mecanicas_codificadas_26592211.html"];
contentPage.processPage.elementUrls["_OSVfEJ_wEeuTPu9eU-Afkw"] = ["Artista gráfico","indie_game_process_rpp/deliveryprocesses/artista_grfico_B19C9D49.html"];
contentPage.processPage.elementUrls["_TCPZNZ_vEeuTPu9eU-Afkw"] = ["Mecanicas de recompensa","indie_game_process_rpp/deliveryprocesses/mecanicas_de_recompensa_10C5B7F4.html"];
contentPage.processPage.elementUrls["_OSU4AJ_wEeuTPu9eU-Afkw"] = ["Publicar jogo","indie_game_process_rpp/deliveryprocesses/publicar_jogo_8C6C26BC.html"];
contentPage.processPage.elementUrls["_kAL9hJ_uEeuTPu9eU-Afkw"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_7E714AB3.html"];
contentPage.processPage.elementUrls["_cFhraKFfEeuqN_L_TCme-A"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_FED02811.html"];
contentPage.processPage.elementUrls["_B9ctYJ_tEeuTPu9eU-Afkw"] = ["Visão geral","indie_game_process_rpp/deliveryprocesses/Visão geral_E5A5DB26.html"];
contentPage.processPage.elementUrls["_lGON8J_tEeuTPu9eU-Afkw"] = ["Objetivo do jogo","indie_game_process_rpp/deliveryprocesses/objetivo_do_jogo_B1367E39.html"];
contentPage.processPage.elementUrls["_ebKZQZ_vEeuTPu9eU-Afkw"] = ["Mecanicas requisitadas","indie_game_process_rpp/deliveryprocesses/mecanicas_requisitadas_4DB94DA4.html"];
contentPage.processPage.elementUrls["_exgSIZ_uEeuTPu9eU-Afkw"] = ["Inimigos","indie_game_process_rpp/deliveryprocesses/Inimigos_9A7EB19E.html"];
contentPage.processPage.elementUrls["_vfFpxJ_uEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_2339E75A.html"];
contentPage.processPage.elementUrls["_LX35EZ_wEeuTPu9eU-Afkw"] = ["Publicar jogo","indie_game_process_rpp/deliveryprocesses/Publicar jogo_5EE91413.html"];
contentPage.processPage.elementUrls["_HaYIwp_wEeuTPu9eU-Afkw"] = ["Game Designer","indie_game_process_rpp/deliveryprocesses/game_designer_7C9F7E72.html"];
contentPage.processPage.elementUrls["_HaYIxp_wEeuTPu9eU-Afkw"] = ["Programador","indie_game_process_rpp/deliveryprocesses/programador_41316091.html"];
contentPage.processPage.elementUrls["_-PwBxp_uEeuTPu9eU-Afkw"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_C860294.html"];
contentPage.processPage.elementUrls["_XY0EoqFfEeuqN_L_TCme-A"] = ["Arte conceitual de inimigos","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_inimigos_D4299F2.html"];
contentPage.processPage.elementUrls["_ebJLJp_vEeuTPu9eU-Afkw"] = ["Músico","indie_game_process_rpp/deliveryprocesses/msico_B56203F4.html"];
contentPage.processPage.elementUrls["_aw7jMZ_vEeuTPu9eU-Afkw"] = ["Requisitos de level","indie_game_process_rpp/deliveryprocesses/Requisitos de level_EBE85AE5.html"];
contentPage.processPage.elementUrls["_UaciSJ_vEeuTPu9eU-Afkw"] = ["Arte conceitual de inimigos","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_inimigos_1B726598.html"];
contentPage.processPage.elementUrls["_msrjhJ_vEeuTPu9eU-Afkw"] = ["Mecanicas de perigo","indie_game_process_rpp/deliveryprocesses/mecanicas_de_perigo_1ADAA56F.html"];
contentPage.processPage.elementUrls["_kALWcJ_uEeuTPu9eU-Afkw"] = ["Caracteristicas dos inimigos","indie_game_process_rpp/deliveryprocesses/caracteristicas_dos_inimigos_C18F54B6.html"];
contentPage.processPage.elementUrls["_UaciSp_vEeuTPu9eU-Afkw"] = ["Arte conceitual de personagem","indie_game_process_rpp/deliveryprocesses/arte_conceitual_de_personagem_14A959BE.html"];
contentPage.processPage.elementUrls["_HEzW5J_vEeuTPu9eU-Afkw"] = ["Enredo do personagem","indie_game_process_rpp/deliveryprocesses/enredo_do_personagem_3663F4BE.html"];
contentPage.processPage.elementUrls["_8WUs0Z_sEeuTPu9eU-Afkw"] = ["Concepção","indie_game_process_rpp/deliveryprocesses/Concepção_DB3A79F3.html"];
contentPage.processPage.elementUrls["_UaciUJ_vEeuTPu9eU-Afkw"] = ["Jogos similares","indie_game_process_rpp/deliveryprocesses/jogos_similares_A49629D6.html"];
contentPage.processPage.elementUrls["_HaXhsJ_wEeuTPu9eU-Afkw"] = ["Refinar jogo","indie_game_process_rpp/deliveryprocesses/refinar_jogo_712101D0.html"];
contentPage.processPage.elementUrls["_WE7jnJ_uEeuTPu9eU-Afkw"] = ["Mundo do jogo","indie_game_process_rpp/deliveryprocesses/mundo_do_jogo_2723F92B.html"];
contentPage.processPage.elementUrls["_HEzW4J_vEeuTPu9eU-Afkw"] = ["Back story personagem","indie_game_process_rpp/deliveryprocesses/back_story_personagem_71D2129F.html"];
